config/routes.rb
Rails.application.routes.draw do

  get 'budgets/index'

  resources :budgets do
      resources :paychecks, :step_ones, :debts, :fixed_monthly_expenses
      resources :paychecks do
          resources :paycheck_deductions
      end
  end
  root 'budgets#index'

end

app/models/paycheck.rb
class Paycheck < ActiveRecord::Base

    belongs_to :budget
    has_many :paycheck_deductions

        validates :name, presence: true
        validates :amount, presence: true

        monetize :amount

    def net_pay
        net_pay_amt =  BigDecimal.new(self.amount.to_s)

        net_pay_amt = net_pay_amt - BigDecimal.new(self.paycheck_deductions.sum(:amount).to_s)

        return net_pay_amt
    end


end

app/controllers/paycheck_controller.rb
class PaychecksController < ApplicationController

        def new
                @paycheck = Paycheck.new
        end

        def create
                @paycheck = Paycheck.new(paycheck_params)
                @paycheck.save
                redirect_to :back
        end

  def update
          @paycheck = Paycheck.find(params[:id])
          if @paycheck.update(paycheck_params)
                  redirect_to :back
          else
                  render 'edit'
          end
  end

  def edit
          @paycheck = Paycheck.find(params[:id])
  end  

  private
  
  def paycheck_params
          params.require(:paycheck).permit(:name, :amount)
  end
end

app/controllers/paychecks_controller.rb
class PaychecksController < ApplicationController

    def new    
        @budget = Budget.find(params[:budget_id])
        @paycheck = Paycheck.new
    end

     
    def create
        @budget = Budget.find(params[:budget_id])
        if @budget.paychecks.create(paycheck_params)
            redirect_to budget_paychecks_path(@budget)
        else
            render 'new'
        end
    end

    
    def edit
        @budget = Budget.find(params[:budget_id])
        @paycheck = @budget.paychecks.find(params[:id])
    end  

    
    def update  
        @budget = Budget.find(params[:budget_id])
        if @budget.paychecks.find(params[:id]).update(paycheck_params)
            redirect_to budget_paychecks_path(@budget)
        else
            render 'edit'
        end
    end
    
    
    def destroy    
        @budget = Budget.find(params[:budget_id])
        @paycheck = @budget.paychecks.find(params[:id])

        @paycheck.paycheck_deductions.destroy_all
        @paycheck.destroy
 
        redirect_to budget_paychecks_path(@budget)
    end      
      
 
    def index
        @budget = Budget.find(params[:budget_id])
    end

    
    def show
        @budget = Budget.find(params[:budget_id])
        @paycheck = @budget.paychecks.find(params[:id])
    end


    private

    def paycheck_params
        params.require(:paycheck).permit(:name, :amount)
    end

end

app/helpers/paycheck_helper.rb
module PaycheckHelper
end

app/views/paychecks/_form.html.erb
<%= form_for [@budget, @paycheck] do |f| %>
 
  <% if @paycheck.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@paycheck.errors.count, "error") %> prohibited
        this paycheck from being saved:
      </h2>
      <ul>
        <% @paycheck.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount, data: {autonumeric: true} %> 
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/paychecks/edit.html.erb
<h1>Edit Paycheck</h1>
 
<%= render 'form' %>

<%= link_to 'Back', budget_paychecks_path(@budget) %>

app/views/paychecks/index.html.erb
<h1>Paychecks</h1>
<%= link_to 'New Paycheck', new_budget_paycheck_path(@budget) %>
<table id=expenses>
  <tr>
    <th>Name</th>
    <th>Gross</th>
    <th>Net</th>
    <th colspan="3"></th>
  </tr>

  <%
    i=0
    table_row_style = ""
    @budget.paychecks.each do |paycheck|
      i += 1
      if i%2 == 0
              table_row_style = "class=alt"
      else
              table_row_style = ""
      end 
  %>
    <tr <%=table_row_style%> >
      <td><%= paycheck.name %></td>
      <td><div id=currency_symbol>$</div><div id=currency_amount><%= humanized_money paycheck.amount %></div></td>
      <td><div id=currency_symbol>$</div><div id=currency_amount><%= paycheck.net_pay %></div></td>
      <td><%= link_to 'Add Deductions', budget_paycheck_path(@budget, paycheck) %></td>
      <td><%= link_to 'Edit', edit_budget_paycheck_path(@budget, paycheck) %></td>
      <td><%= link_to 'Delete', budget_paycheck_path(@budget, paycheck),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>
<%= link_to 'Back', budgets_index_path %>

app/views/paychecks/new.html.erb
<h1>New Paycheck</h1>
 
<%= render 'form' %>

<%= link_to 'Back', budget_paychecks_path(@budget) %>

app/views/paychecks/show.html.erb
<div id=paycheck_header><%= @paycheck.name %>: Gross Pay 
<%= humanized_money_with_symbol @paycheck.amount %>
</div>

<div id=deduction_table>
    <div id=deduction_heading>
        <div id=deduction_cell>
            Deduction Name
        </div>
        <div id=deduction_cell>
            Amount
        </div>
        <div id=deduction_cell>
            Pre Tax?
        </div>
        <div id=deduction_cell></div>
    </div>
    <%= render @paycheck.paycheck_deductions %>
</div>
    <%= render 'paycheck_deductions/form' %>
<br>
<br>
<%= link_to 'Back', budget_paychecks_path(@budget) %>