config/routes.rb
Rails.application.routes.draw do

  get 'budgets/index'

  resources :budgets do
      resources :paychecks, :step_ones, :debts, :fixed_monthly_expenses
      resources :paychecks do
          resources :paycheck_deductions
      end
  end
  root 'budgets#index'

end

app/models/debt.rb
class Debt < ActiveRecord::Base

  belongs_to :budget

  validates :name, presence: true
  validates :balance, presence: true
  validates :minimum_monthly_payment, presence: true
  validates :interest_rate, presence: true
  
  monetize :balance
  monetize :minimum_monthly_payment
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
	
    def new
        @budget = Budget.find(params[:budget_id])
        @debt = Debt.new
	end
	
    
    def create
        @budget = Budget.find(params[:budget_id])
		if @budget.debts.create(debt_params)	
            redirect_to budget_debts_path(@budget)
		else
			render 'new'
		end
	end

	
	def edit
		@budget = Budget.find(params[:budget_id])
        @debt = @budget.debts.find(params[:id])
	end
    
    
	def update
		@budget = Budget.find(params[:budget_id])
        if @budget.debts.find(params[:id]).update(debt_params)
    	    redirect_to budget_debts_path(@budget)
        else
            render 'edit'
    	end
	end
    
   
    def destroy
		@budget = Budget.find(params[:budget_id])
        @budget.debts.find(params[:id]).destroy
 
		  redirect_to budget_debts_path(@budget)
	end
	


	def index
		@budget = Budget.find(params[:budget_id])
	end
	

	private
		def debt_params
			params.require(:debt).permit(:name, :balance, :minimum_monthly_payment, :interest_rate)
    end
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/views/debts/_form.html.erb
<%= form_for [@budget, @debt] do |f| %>
 
  <% if @debt.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@debt.errors.count, "error") %> prohibited
        this debt from being saved:
      </h2>
      <ul>
        <% @debt.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :balance %><br>
    <%= f.text_field :balance, data: {autonumeric: true} %> 
  </p>
  <p>
     <%= f.label :minimum_monthly_payment %><br>
     <%= f.text_field :minimum_monthly_payment, data: {autonumeric: true} %>
     </p> 
  <p>
      <%= f.label :interest_rate %><br>
      <%= f.text_field :interest_rate, data: {autonumeric: true} %>
 </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/debts/edit.html.erb
<h1>Edit Debt</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', budget_debts_path(@budget) %>

app/views/debts/index.html.erb
<h1>Debts</h1>
<%= link_to 'New Debt', new_budget_debt_path(@budget) %>
<table id=expenses>
  <tr>
    <th>Name</th>
    <th>Balance</th>
    <th>Minimum Monthly Payment</th>
    <th>Interest Rate <th>
    <th colspan="2"></th>
  </tr>

  <%
    i=0
    table_row_style = ""
    @budget.debts.each do |debt| 
      i += 1
      if i%2 == 0
              table_row_style = "class=alt"
      else
              table_row_style = ""
      end 
  %>
    <tr <%=table_row_style%> >
      <td><%= debt.name %></td>
      <td><div id=currency_symbol>$</div><div id=currency_amount><%= humanized_money debt.balance %></div></td>
      <td><div id=currency_symbol>$</div><div id=currency_amount><%= humanized_money debt.minimum_monthly_payment %></div></td>
      <td><div id=currency_symbol>%</div><div id=currency_amount><%= humanized_money debt.interest_rate %></div></td>
      <td><%= link_to 'Edit', edit_budget_debt_path(@budget, debt) %></td>
      <td><%= link_to 'Delete', budget_debt_path(@budget, debt),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>
<%= link_to 'Back', budgets_index_path %>

app/views/debts/new.html.erb
<h1>New Debt</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', budget_debts_path(@budget) %>