config/routes.rb
Rails.application.routes.draw do

  get 'budgets/index'

  resources :budgets do
      resources :paychecks, :step_ones, :debts, :fixed_monthly_expenses
      resources :paychecks do
          resources :paycheck_deductions
      end
  end
  root 'budgets#index'

end

app/models/budget.rb
class Budget < ActiveRecord::Base

    has_many :paychecks
    has_many :paycheck_deudctions, through: :paychecks
    has_many :fixed_monthly_expenses
    has_many :debts
    has_one :step_one    

    validates :name, presence: true

    monetize :monthly_financial_goals_amount


    def total_monthly_gross_income
        biweekly_gross = self.paychecks.sum(:amount)
        monthly_gross = calculate_monthly(biweekly_gross)
        return BigDecimal.new(monthly_gross.to_s)
    end


    def total_monthly_deductions
        biweekly_deductions = 0.0 
        self.paychecks.each do |paycheck|
            biweekly_deductions += paycheck.paycheck_deductions.sum(:amount)
        end

        monthly_deductions = calculate_monthly(biweekly_deductions)
        return BigDecimal.new(monthly_deductions.to_s)
    end

    def monthly_net_income
        monthly_net = self.total_monthly_gross_income - self.total_monthly_deductions

        return BigDecimal.new(monthly_net.to_s)
    end

    def monthly_fixed_expenses
        monthly_expenses = BigDecimal.new(self.fixed_monthly_expenses.sum(:amount).to_s)
        return monthly_expenses
    end

    def remaining_after_all_expenses
        remaining = self.monthly_net_income - self.monthly_fixed_expenses - self.monthly_financial_goals_amount - self.minimum_monthly_debt_payments_sum - self.non_monthly_expense_amount
        return BigDecimal.new(remaining.to_s)
    end

    def minimum_monthly_debt_payments_sum
        sum = BigDecimal.new(self.debts.sum(:minimum_monthly_payment).to_s)
        return sum
    end

    def total_non_monthly_expenses
        non_monthly = 0.0;
        non_monthly += self.non_monthly_expense_amount

        if self.use_biweekly_extra_for_non_monthly_expenses
            self.paychecks.each do |paycheck|
                non_monthly += paycheck.net_pay
            end
        end

        non_monthly *= 2

        return BigDecimal.new(non_monthly.to_s)
    end

    private
    def calculate_monthly(biweekly_amount)
        if self.calculate_income_using_two_biweekly_periods
            return biweekly_amount * 2
        else
            return ((biweekly_amount*26)/12).round(2)
        end
    end
    
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

    def index
        @budget = Budget.first

        if (@budget == nil)
            redirect_to new_budget_path
        else
            @step_one = @budget.step_one
            
            if (@step_one == nil)
                @step_one = @budget.create_step_one(current_balance: 0, goal_balance: 0)
            end
        end
        @budget_logic = BudgetLogic.new(@budget)
    end

    def new
        @budget = Budget.new
    end

    def create
        @budget = Budget.new(budget_params)
        if @budget.save
            redirect_to budgets_index_path
        else
            render 'new'
        end
    end

    def edit
        @budget = Budget.find(params[:id])
    end

    def update 
        @budget=Budget.find(params[:id])
        if (@budget.update(budget_params))
            redirect_to budgets_index_path
        else
            render 'edit'
        end
    end


    private

    def budget_params
        params.require(:budget).permit(:name, :monthly_financial_goals_amount, :calculate_income_using_two_biweekly_periods, :non_monthly_expense_amount, :use_biweekly_extra_for_non_monthly_expenses)
    end 

end

app/helpers/budget_helper.rb
module BudgetHelper
end

app/views/budgets/_form.html.erb
<%= form_for @budget do |f| %>
    
    <% if @budget.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@budget.errors.count, "error") %> prohibited this budget from being saved:
            </h2>
            <ul>
                <% @budget.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <span id=form_descriptions>On this page we will setup some basic information about your budget. You can choose how you would like to calculate your montly income, how you would like to account for non-monthly expenses, and how much of your regular monthly income you would like to reserve to accomplish your financial goals.</span>
    <br>
    <br>
    <span id=form_labels>
        *Budget Name: <%= f.text_field :name %> 
    </span>
    
    <br>
    <br>
    <br>
    <span id=budget_page_heading>
        Monthly Financial Goals
    </span>
    <br>
    <span id=form_descriptions>
        This is the amount of your income that will be dedicated to accomplishing your financial goals each month. This amount is the first to come out of your net pay and is used to accomplish your goals including Funding an Emergency Account, Becommming Debt Free, Investing, etc.
    </span>
    <br>
    <span id=form_labels>
        Amount:
        <%= f.text_field :monthly_financial_goals_amount, data: {autonumeric: true} %>
    </span>
    
    <br>
    <br>
    <br>
    <span id=budget_page_heading>
        Calculating Monthly Income with BiWeekly Pay    
    </span>
    <br>
    <span id=form_descriptions>
        Select this option if you would like your monthly income calculated using two biweekly periods. If this box is unchecked, your income will be caluclated using a monthly average to account for the two extra biweekly periods annually.
    </span>
    <br>
    <span id=form_labels>
        Calculate Using BiWeekly Periods?
        <%= f.check_box :calculate_income_using_two_biweekly_periods %>      
    </span>



    <br>
    <br>
    <br>
    <span id=budget_page_heading>
        Non Monthly Expenses    
    </span>
    <br>
    <span id=form_descriptions>
        This is the amount of your income that will be dedicated to your non monthly expenses including gifts, annual premiums, annual auto registration, home maintenance, quarterly taxes, etc.
    </span>
    <br>

    <span id=form_labels>
        Calculate Using BiWeekly Periods?
        <%= f.text_field :non_monthly_expense_amount, data: {autonumeric: true}  %>
    </span>
     

 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/budgets/edit.html.erb
<h1>Edit Budget</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/budgets/index.html.erb
<div id=budget_table>
    
    <div id=budget_heading>
        <div id=budget_heading_cell>
            Income 
            <span id=edit_link>                
                <%= link_to 'Edit', budget_paychecks_path(@budget) %>
            </span>
        </div>
    </div>

    <div id=budget_row>
        <div id=budget_cell>
            Gross Income
        </div>
        <div id=budget_cell>
            <span id=currency_sign> $ </span>
            <span id=money_text> 
                <%= humanized_money @budget.total_monthly_gross_income %> 
            </span>
        </div>
    </div>

    <div id=budget_row>
        <div id=budget_cell>
            Less Total BiWeekly Deductions/Expenses
        </div>
        <div id=budget_cell>
            <span id=currency_sign> $ </span>
            <span id=money_text>
                -<%= humanized_money @budget.total_monthly_deductions %> 
            </span>
        </div>
    </div>

    <div id=budget_heading>
        <div id=budget__headingcell>
            Monthly Net Income
        </div>
        <div id=budget_heading_cell>
            <span id=currency_sign> $ </span>
            <span id=money_text>
                <%= humanized_money @budget.monthly_net_income %> 
            </span>
        </div>
    </div>
    
    
    <div id=budget_heading>
        <div id=budget_heading_cell>
            Monthly Amount for Financial Goals 
            <span id=edit_link>
                <%= link_to 'Edit', edit_budget_path(@budget) %>
            </span>
        </div>
        <div id=budget_heading_cell>
            <span id=currency_sign>$</span>
            <span id=money_text> 
                <%= @budget.monthly_financial_goals_amount %> 
            </span>
        </div>
    </div>


    <div id=budget_heading>
        <div id=budget_heading_cell>
            Monthly Fixed Expenses 
            <span id=edit_link>
                <%= link_to 'Edit', budget_fixed_monthly_expenses_path(@budget) %>
            </span>
        </div>
        <div id=budget_heading_cell>
            <span id=currency_sign>$</span>
            <span id=money_text> 
                <%= @budget.monthly_fixed_expenses %> 
            </span>
        </div>
    </div>
    

    <div id=budget_heading>
        <div id=budget_heading_cell>
            Monthly Debt Payments 
            <span id=edit_link>
                <%= link_to 'Edit', budget_debts_path(@budget) %>
            </span>
        </div>
  
        <div id=budget_heading_cell>
            <span id=currency_sign>$</span>
            <span id=money_text> 
                <%= @budget.minimum_monthly_debt_payments_sum %> 
            </span>
        </div>
    </div>


    <div id=budget_heading>
        <div id=budget_heading_cell>
            Amount Remaining for Spending 
            <span id=edit_link>
                <%= link_to 'Edit', edit_budget_path(@budget) %>
            </span>
        </div>
        <div id=budget_heading_cell>
            <span id=currency_sign>$</span>
            <span id=money_text> 
                <%= @budget.remaining_after_all_expenses %> 
            </span>
        </div>
    </div>



    <div id=budget_heading><br><br></div>



    <div id=budget_heading>
        <div id=budget_heading_cell>
            Step 1: Initial Emergency Fund
            <span id=edit_link>
                <%= link_to 'Edit', edit_budget_step_one_path(@budget, @step_one) %>
            </span>
        </div>
    </div>
    
    <div id=budget_row>
        <div id=budget_cell>
            Your Goal
        </div>
        <div id=budget_cell>
            <span id=currency_sign>$</span>
            <span id=money_text> 
                <%= humanized_money @step_one.goal_balance %> 
            </span>
        </div>
    </div>
    
    <div id=budget_row>
        <div id=budget_cell>
            Current Balance
        </div>
        <div id=budget_cell>
            <span id=currency_sign>$</span>
            <span id=money_text> 
                <%= humanized_money @step_one.current_balance %> 
            </span>
        </div>
    </div>
    
    <div id=budget_row>
        <div id=budget_cell>
            Completion Date
        </div>
        <div id=budget_cell>
            <span id=money_text>
                <%= @budget_logic.step_one_met_date(Time.now).strftime('%D') %>
            </span> 
        </div>
    </div>



    <div id=budget_heading><br><br></div>



    <div id=budget_heading>
        <div id=budget_heading_cell>
            Step 2: Payoff All Debt Excluding Mortgage
            <span id=edit_link>               
                <%= link_to 'Edit', budget_debts_path(@budget) %>
            </span>
        </div>
    </div>
</div>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%=render 'form' %>

<%= link_to 'Back', :back %>